package dev.zsithious.socialcues.core.client;

import java.util.Objects;

import dev.zsithious.socialcues.core.state.Activity;

/**
 * DESIGN.md §7 P4a — the layout of Social Cues' own hand-drawn icon sheet:
 * an 8x8 grid of 16x16 monochrome (white + alpha, tintable by the renderer)
 * cells, generated by {@code tools/gen_icons.py} and committed as
 * {@code mc-shared/src/main/resources/assets/socialcues/textures/gui/cues.png}
 * (shared, unmodified, by every {@code :mc:<version>} project). Per
 * CLEANROOM.md, none of this artwork is derived from WATUT in any way — it
 * is drawn fresh by this repo's own generator script.
 *
 * <p>This class is the single source of truth for "which cell is which", so
 * the atlas layout, the generator script, and P4b's render code can never
 * silently drift apart from one another: change a cell assignment here,
 * regenerate the PNG with the same script (its cell layout mirrors this
 * class exactly), done.
 *
 * <p><b>Layout:</b> one cell per {@link Activity}, assigned through an
 * exhaustive {@code switch} expression (not {@code ordinal()}) so that
 * adding a new {@code Activity} constant without also giving it an icon cell
 * is a <em>compile</em> error here, not a silent gap discovered later at
 * render time — see {@link #cellFor(Activity)}. One further cell,
 * {@link #SLEEPY_CELL}, is reserved for the {@code CueFlags#SLEEPY} variant
 * of {@link Activity#AFK} (DESIGN.md §4: "AFK eşiğinin 2 katını geçti"): a
 * renderer substitutes it for {@code cellFor(Activity.AFK)} when that flag
 * is set, never a third {@code Activity} value — DESIGN.md §4 already models
 * "sleepy" as a flag layered on {@code AFK}, not a separate activity.
 *
 * <p>The remaining cells (there are {@link #GRID_COLUMNS} *
 * {@link #GRID_ROWS} in total) are reserved headroom for P5's richer poses
 * and any accessibility variant DESIGN.md §9's {@code textOnly}/{@code
 * reducedMotion} modes turn out to need; they are simply left blank
 * (fully transparent) by the generator today.
 */
public final class CueIconAtlas {

    /** Grid layout, DESIGN.md §7: "8×8 hücreli". */
    public static final int GRID_COLUMNS = 8;
    public static final int GRID_ROWS = 8;

    /** Source resolution of one cell; P4b scales this up/down per layer (billboard vs. 8x8 tab-list icon, DESIGN.md §7). */
    public static final int CELL_PIXELS = 16;

    public static final int TEXTURE_WIDTH = GRID_COLUMNS * CELL_PIXELS;
    public static final int TEXTURE_HEIGHT = GRID_ROWS * CELL_PIXELS;

    /**
     * Path relative to the mod's assets root (i.e. the Fabric/vanilla
     * {@code Identifier}'s path half — the namespace, {@code socialcues},
     * is not repeated here so this stays usable from pure Java).
     */
    public static final String TEXTURE_PATH = "textures/gui/cues.png";

    /** One past the last {@link Activity}'s cell index — the AFK+SLEEPY variant's dedicated cell. */
    public static final int SLEEPY_CELL = Activity.values().length;

    private CueIconAtlas() {
    }

    /**
     * The atlas cell (row-major, 0-based, {@code row * GRID_COLUMNS + column})
     * holding {@code activity}'s default icon. Exhaustive over every current
     * {@link Activity} value by construction — see the class Javadoc for why
     * that is a compile-time guarantee, not just a runtime one; {@link
     * CueIconAtlasTest} additionally verifies the resulting cells are
     * in-range and pairwise distinct.
     */
    public static int cellFor(Activity activity) {
        Objects.requireNonNull(activity, "activity");
        return switch (activity) {
            case NORMAL -> 0;
            case TYPING_CHAT -> 1;
            case TYPING_COMMAND -> 2;
            case TYPING_SIGN -> 3;
            case TYPING_BOOK -> 4;
            case IN_SCREEN -> 5;
            case AFK -> 6;
            case SPEAKING -> 7;
        };
    }

    /** 0-based column of {@code cellIndex} within the grid. */
    public static int column(int cellIndex) {
        return cellIndex % GRID_COLUMNS;
    }

    /** 0-based row of {@code cellIndex} within the grid. */
    public static int row(int cellIndex) {
        return cellIndex / GRID_COLUMNS;
    }

    /** Left-edge U texture coordinate (0.0-1.0) of {@code cellIndex}, for a renderer that samples by UV rather than pixel rect. */
    public static float minU(int cellIndex) {
        return (float) (column(cellIndex) * CELL_PIXELS) / TEXTURE_WIDTH;
    }

    public static float maxU(int cellIndex) {
        return (float) ((column(cellIndex) + 1) * CELL_PIXELS) / TEXTURE_WIDTH;
    }

    public static float minV(int cellIndex) {
        return (float) (row(cellIndex) * CELL_PIXELS) / TEXTURE_HEIGHT;
    }

    public static float maxV(int cellIndex) {
        return (float) ((row(cellIndex) + 1) * CELL_PIXELS) / TEXTURE_HEIGHT;
    }
}
